### ISSUE TITLE
Adding a license file

### ISSUE THREAD

**Issue by BlasterAlex** [PhilippeOlivier/break-the-code#1]
Hi, thanks for publishing this development in public. I would like to use it as part of my fork project and modify it (change the simulator logic and add support for 3-4 players). 

At the moment I am restricted to use the code without any license. Could you please add a license file? 

You can use this tool to make it easier to choose the right license for you: https://ufal.github.io/public-license-selector/.

**Comment by BlasterAlex** [comment]
I've created PR #2 to add a license file, please take a look as you get a chance

**Comment by PhilippeOlivier** [comment]
I'd be happy to use the GPL-3.0 license. If that suits you, update your PR accordingly and I will merge it.

**Comment by BlasterAlex** [comment]
Changed the license used to GPL-3.0, thanks for your reply
